image: golang:latest

variables:
  REPO_NAME: gitlab.com/vfaergestad/news-scraper
  DOCKER_HUB_LINK: https://index.docker.io/v1/
  IMAGE_NAME: news-scraper

stages:
  - build

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [ "" ]
  script:
    - mkdir -p /kaniko/.docker
    - echo $FIRESTORE_AUTH | base64 -d > ${CI_PROJECT_DIR}/serviceAccountKey.json
    - echo "{\"auths\":{\"$DOCKER_HUB_LINK\":{\"auth\":\"$(echo -n vfaergestad:${DOCKER_REGISTRY_PASSWORD} | base64)\"}}}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "vfaergestad/$IMAGE_NAME:latest"
      --force