# cronjob.yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: news-scraper
spec:
  schedule: "0 */12 * * *"
  concurrencyPolicy: Allow
  startingDeadlineSeconds: 120
  suspend: false
  successfulJobsHistoryLimit: 10
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: news-scraper
              image: vfaergestad/news-scraper:latest
          restartPolicy: Never